version: "3.8"

services:

   reverse_proxy:
      image: traefik:v1.7.24-alpine
      command: --api --docker --docker.swarmMode --docker.domain=${DOMAIN.LOCAL} --docker.watch --logLevel=DEBUG 
      networks:
         - net-proxy
      dns:
         - ${DNS_IP}
      dns_search: ${FQDN.DOMAIN.LOCAL}
      ports: #PORTAS NO QUAL O TRAEFIK FICARÁ OUVINDO PARA GERENCIAS OS REQUESTS PARA OS SEUS RESPECTIVOS CONTAINERS.
         - target: 80
         published: 80
         protocol: tcp
         mode: host
         - target: 8080
         published: 8080
         protocol: tcp
         mode: host
         - target: 443
         published: 443
         protocol: tcp
         mode: host
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock" #CAMINHO DO SOCK DO DOCKER.
         - "/etc/localtime:/etc/localtime:ro"
         - "traefik_certs:/certs"
         - "/mnt/gluster_docker/volumes/traefik_config/_data/traefik.toml:/etc/traefik/traefik.toml"
      deploy:
         mode: global
         placement:
            constraints:
               - node.role == manager #FLAG PARA QUE O TRAEFIK SUBA APENAS EM NÓS MASTERS.
         update_config:
            parallelism: 1
            delay: 10s

networks: 
   net-proxy:
      external: true
      driver: overlay

volumes:
   traefik_certs:
      driver_opts:
         type: "none"
         o: "bind"
         device: "/mnt/gluster_docker/volumes/traefik_certs/_data"